dist: precise
language: php

php:
  - '5.3'
  - '5.5'
  - '7.0'
  - '7.1'
  - '7.2'

branches:
  - master
  - develop

before_script:
  - composer install

script: vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
